# Generated by Django 5.0.2 on 2025-10-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admin_login',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=75)),
                ('breed', models.CharField(max_length=75)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.IntegerField()),
                ('fur_type', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=75)),
                ('type', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('noice_level', models.CharField(choices=[('Quiet', 'Quiet'), ('Moderate', 'Moderate'), ('Loud', 'Loud')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('username', models.CharField(max_length=75)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doct_id', models.CharField(max_length=50, unique=True)),
                ('doct_name', models.CharField(max_length=75)),
                ('category', models.CharField(max_length=75)),
                ('hospital', models.CharField(max_length=75)),
                ('place', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APT_id', models.CharField(max_length=50, unique=True)),
                ('pet_name', models.CharField(max_length=75)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('hospital_name', models.CharField(max_length=75)),
                ('place', models.CharField(max_length=75)),
                ('other_query', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
            ],
        ),
    ]
